-- CAE Knowledge Base V4 — sample data (generated by scripts/build-seed.mjs from data/knowledge-base.json)
-- Run AFTER supabase/schema.sql. Safe to re-run: rows are matched by key / id and updated.
-- All figures in the sample article are generated illustrations (mock) served from the site's own assets/figures folder.

insert into public.software_categories (key, label, parent_key, description, is_active, sort_order) values
  ($q$hm$q$, $q$HyperWorks$q$, null, $q$包含 HyperMesh、OptiStruct 相關的除錯、設定與分析問題$q$, true, 0),
  ($q$lsdyna$q$, $q$LS-DYNA$q$, null, $q$顯式動力學分析：接觸、能量、穩定性與計算中止相關問題$q$, true, 30),
  ($q$hypermesh-2$q$, $q$HyperMesh$q$, $q$hm$q$, $q$幾何處理、網格、模型建構相關問題$q$, true, 10),
  ($q$optistruct$q$, $q$OptiStruct$q$, $q$hm$q$, $q$結構分析、最佳化相關問題$q$, true, 20)
on conflict (key) do update set label = excluded.label, parent_key = excluded.parent_key, description = excluded.description,
  is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  '27e17f32-190d-5db1-a797-f86d706088ae', $q$optistruct$q$, $q$*** ERROR # 1953：模型存在剛體模態，線性靜態分析無法求解$q$, array[$q$solver-error$q$, $q$boundary-condition$q$, $q$rigid-body$q$]::text[],
  $q$執行 Linear Static 時 solver 在組裝剛度矩陣後中止：
`*** ERROR # 1953: The model has rigid body modes.`
.out 檔列出 grid 120334 自由度 1、2、6 無約束。$q$,
  $q$左右支架以 `RBE2` 連接到螺栓，但螺栓本體只有 1D `CBAR`，旋轉自由度沒有傳到殼元素；另外 SPC 只拘束了 T1–T3。$q$,
  $q$1. 用 **Tools › Model Checker** 找出未連接的 component
2. 在螺栓兩端補 `RBE2`，dependent DOF 設 `123456`
3. 先跑 `PARAM,CHECKEL,YES` + `PARAM,GRDPNT,0` 確認質量與約束
4. 仍不確定時加 `PARAM,INREL,-2` 做慣性釋放檢查$q$,
  array[$q$增加 SPC 到 123456 —— 反而把真實邊界條件改掉了$q$, $q$把 AUTOSPC 關掉$q$]::text[], $q$常見於組件拼裝後第一次提交，建議把 Model Checker 變成提交前的固定步驟。$q$, $q$Altair OptiStruct Help — Rigid Body Modes$q$,
  $q$[]$q$::jsonb, 0, '2026-09-27T17:51:30.052Z', '2026-09-30T17:51:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  '14528e61-1116-548e-9ab7-65916ede4195', $q$optistruct$q$, $q$Insufficient memory：大型模型求解時記憶體不足$q$, array[$q$solver-error$q$, $q$performance$q$, $q$memory$q$]::text[],
  $q$約 480 萬自由度的模型在 `SOLVE` 階段中止，訊息為 `Insufficient memory allocated, increase -len`。$q$,
  $q$預設 `-len` 太小，且 out-of-core 暫存資料夾指到網路磁碟，I/O 太慢。$q$,
  $q$- 提交參數加上 `-len 32000 -core in`
- 若記憶體不足以 in-core，改 `-core out` 並把 `-tmpdir` 指到本機 SSD
- 使用 `-nt 8` 開啟平行運算$q$,
  '{}'::text[], $q$先用 `-check` 跑一次，.out 會估算 in-core 所需記憶體。$q$, $q$Altair Help / Internal HPC Guide$q$,
  $q$[]$q$::jsonb, 0, '2026-09-26T13:03:30.053Z', '2026-09-29T13:03:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  '811fa4ed-60a8-5462-8e3a-aea3106e8c6c', $q$optistruct$q$, $q$拓樸最佳化結果出現棋盤格（checkerboard）$q$, array[$q$optimization$q$, $q$mesh-quality$q$]::text[],
  $q$密度結果呈現黑白交錯的棋盤格，無法轉成可製造的幾何。$q$,
  $q$沒有設定最小尺寸控制 `MINDIM`，網格尺寸與設計特徵尺寸接近。$q$,
  $q$1. `DTPL` 加上 `MINDIM`，約為平均元素尺寸的 3 倍
2. 視需求加 `MAXDIM` 與製造限制（`DRAW`、`EXTR`）
3. 以 `DISCRETE` 2.0–3.0 提高 0/1 收斂度$q$,
  array[$q$只把網格加密 —— 棋盤格變細但沒有消失$q$]::text[], $q$$q$, $q$$q$,
  $q$[]$q$::jsonb, 0, '2026-09-24T22:39:30.053Z', '2026-09-27T22:39:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  'c0a82511-6795-5e26-9b10-f953022670f5', $q$hypermesh-2$q$, $q$STEP 匯入後幾何破面，free edges 無法補面$q$, array[$q$geometry$q$, $q$cleanup$q$, $q$step$q$]::text[],
  $q$CAD 匯入後出現破面、縫隙，無法產生封閉 mid-surface 或 solid map。Geometry › Free edges 顯示紅色邊界約 120 條。$q$,
  $q$CAD 輸出公差（0.01 mm）小於 HyperMesh 的 cleanup tolerance，縫合沒有成功。$q$,
  $q$1. **Geometry › Autocleanup** 前先把 cleanup tol 設成 0.1
2. 使用 **Edge Edit › Toggle / Equivalence** 合併重複邊
3. 仍開口的區域用 **Surface › Fill** 補面，再 `Stitch`$q$,
  array[$q$重新匯出 IGES —— 破面更多$q$]::text[], $q$請 CAD 端以 AP214 輸出、公差 0.001 mm，品質明顯較好。$q$, $q$Altair HyperMesh Help — Geometry Cleanup$q$,
  $q$[{"src":"assets/figures/fig-01-free-edges.svg","title":"Free edges 顯示紅色邊界","caption":"Geometry › Free edges：匯入後約 120 條自由邊（紅），集中在曲面交界。","section":"symptom","step":0,"order":1,"key":true,"mock":true},{"src":"assets/figures/fig-02-cleanup-tolerance.svg","title":"間隙與 cleanup tolerance","caption":"CAD 間隙約 0.01 mm，超出預設 tol，因此無法自動縫合。","section":"root_cause","step":0,"order":2,"mock":true},{"src":"assets/figures/fig-03-autocleanup-panel.svg","title":"Autocleanup：cleanup tol = 0.1","caption":"先把 cleanup tol 由預設值調為 0.1 再執行。","section":"solution","step":1,"order":3,"mock":true},{"src":"assets/figures/fig-04-edge-equivalence.svg","title":"Edge Edit：合併重複邊","caption":"Toggle / Equivalence 合併重複邊，紅線會轉為綠線。","section":"solution","step":2,"order":4,"mock":true},{"src":"assets/figures/fig-05-surface-fill-stitch.svg","title":"Surface Fill + Stitch","caption":"仍開口的區域補面後再 Stitch。","section":"solution","step":3,"order":5,"mock":true},{"src":"assets/figures/fig-06-before-after.svg","title":"修補前 / 修補後","caption":"free edges 由 120 降至 2，剩餘兩條為倒角尖點。","section":"solution","step":"v","order":6,"mock":true},{"src":"assets/figures/fig-07-autocleanup-warning.svg","title":"Autocleanup 警告訊息","caption":"12 個 surface 縫合失敗；tolerance 小於邊界間隙。","section":"symptom","step":0,"order":7,"mock":true},{"src":"assets/figures/fig-08-mesh-quality.svg","title":"修補後 2D 網格品質","caption":"Jacobian ≥ 0.6 達 99.1%，可繼續產生 solid map。","section":"solution","step":"v","order":8,"mock":true}]$q$::jsonb, 0, '2026-09-27T05:51:30.053Z', '2026-09-30T05:51:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  'ccec1f92-2b8c-51d2-be28-c1edbccdc978', $q$hypermesh-2$q$, $q$Mid-surface 抽取失敗：肋條厚度不一致$q$, array[$q$geometry$q$, $q$midsurface$q$]::text[],
  $q$`Midsurface › Auto Extract` 在薄肋與主體交界處產生缺口，部分肋條沒有被抽出。$q$,
  $q$肋條有拔模角，厚度從 1.8 mm 漸變到 2.6 mm，自動辨識的 thickness pair 不一致。$q$,
  $q$- 改用 **Surface Pair** 手動指定上下面
- 對拔模肋條使用 **Offset** 後再 `Extend` 接回主面
- 厚度以 `Assign thickness from midsurface` 自動回填$q$,
  '{}'::text[], $q$$q$, $q$$q$,
  $q$[]$q$::jsonb, 0, '2026-09-25T17:51:30.053Z', '2026-09-28T17:51:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  '11bcbed1-1651-5208-b298-cf1ebcdedcec', $q$hypermesh-2$q$, $q$Element quality：Jacobian < 0.6 無法通過品質檢查$q$, array[$q$mesh-quality$q$, $q$jacobian$q$]::text[],
  $q$倒角附近的 2D 元素 Jacobian 低於 0.6，約 340 個元素無法通過品質門檻。$q$,
  $q$倒角寬度小於網格尺寸，四邊形元素被壓扁。$q$,
  $q$1. 對小倒角使用 **Defeature › Fillets** 或改成 2 排元素
2. 以 **2D › Qualityindex** 設定目標後執行 `Clean up`
3. 局部改用 trias，比例控制在 5% 以內$q$,
  '{}'::text[], $q$$q$, $q$$q$,
  $q$[]$q$::jsonb, 0, '2026-09-22T22:39:30.053Z', '2026-09-25T22:39:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  '13dd25e0-2c7a-5c6e-a6f2-96363c0f1f88', $q$lsdyna$q$, $q$Negative volume in solid element — 計算中止$q$, array[$q$solver-error$q$, $q$contact$q$, $q$mesh-quality$q$]::text[],
  $q$約 18 ms 時 d3hsp 顯示：
`*** Error 40509 (SOL+509) negative volume in solid element # 2004871`
隨後計算中止。$q$,
  $q$泡棉材料（`*MAT_057`）在大變形下元素嚴重扭曲，且與鋼板之間的接觸剛度不足。$q$,
  $q$1. 泡棉 part 改用 `ELFORM=-1` 或 `ELFORM=-2`
2. 加入 `*CONTACT_INTERIOR` 防止元素翻轉
3. `*CONTROL_SOLID` 設 `ERODE=1`，`*CONTROL_TIMESTEP` 設 `DTMIN`
4. 接觸改 `SOFT=2`$q$,
  array[$q$單純降低時間步長 —— 只延後錯誤出現的時間$q$]::text[], $q$先檢查是否為局部初始穿透造成的扭曲。$q$, $q$LS-DYNA Keyword Manual Vol. I / Internal Test$q$,
  $q$[]$q$::jsonb, 0, '2026-09-27T13:03:30.053Z', '2026-09-30T13:03:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  'f4450e15-f6e1-5a5c-b880-3242c1db4292', $q$lsdyna$q$, $q$Hourglass energy 超過 internal energy 的 10%$q$, array[$q$energy$q$, $q$mesh-quality$q$, $q$hourglass$q$]::text[],
  $q$glstat 中 hourglass energy 在 30 ms 後持續上升，最後約為 internal energy 的 14%。$q$,
  $q$大量使用 `ELFORM=2` 單點積分殼元素，且未設定 hourglass 控制。$q$,
  $q$- `*HOURGLASS` 使用 `IHQ=4`（剛度型），`QM=0.05`
- 高應變區改用 `ELFORM=16` 全積分殼
- 以 `*DATABASE_MATSUM` 找出能量集中的 part$q$,
  '{}'::text[], $q$判斷標準：HG / IE < 10%，局部 part 最好 < 5%。$q$, $q$$q$,
  $q$[]$q$::jsonb, 0, '2026-09-26T01:03:30.053Z', '2026-09-29T01:03:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  '29206e83-6d69-520a-bd61-9f338f4fcec9', $q$lsdyna$q$, $q$*CONTACT 初始穿透警告（initial penetration）$q$, array[$q$contact$q$, $q$geometry$q$]::text[],
  $q$messag 出現大量 `Warning 30204: initial penetration`，部分節點被移動。$q$,
  $q$殼元素厚度造成的接觸厚度重疊，幾何原本就緊貼。$q$,
  $q$1. `*CONTROL_CONTACT` 設 `IGNORE=1`
2. 或在 `*CONTACT_AUTOMATIC_SURFACE_TO_SURFACE` 使用 `SST/MST` 縮小接觸厚度
3. 以 LS-PrePost **Contact › Check** 先修正幾何$q$,
  '{}'::text[], $q$$q$, $q$$q$,
  $q$[]$q$::jsonb, 0, '2026-09-23T22:39:30.053Z', '2026-09-26T22:39:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  'ccf52a39-a2b7-5707-8ff5-79029752bcc8', $q$lsdyna$q$, $q$Mass scaling（DT2MS）造成質量增加過多$q$, array[$q$performance$q$, $q$energy$q$, $q$mass-scaling$q$]::text[],
  $q$d3hsp 顯示 added mass 為原始質量的 6.8%，動態結果明顯偏移。$q$,
  $q$`DT2MS` 目標時間步長設得太大，少數小元素被大量加質量。$q$,
  $q$- 先找出控制時間步長的小元素並重劃網格
- `DT2MS` 設定成 added mass < 2% 的值
- 以 `*DATABASE_GLSTAT` 監控 added mass$q$,
  array[$q$整體放大 DT2MS 以縮短計算時間$q$]::text[], $q$$q$, $q$$q$,
  $q$[]$q$::jsonb, 0, '2026-09-20T22:39:30.053Z', '2026-09-23T22:39:30.053Z')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

