// Generates supabase/seed.sql from data/knowledge-base.json (the local sample data).
//   node scripts/build-seed.mjs          writes supabase/seed.sql
//   node scripts/build-seed.mjs --rows   prints the rows as JSON (what the database will return)
// Entry ids become deterministic UUIDs, so re-running the seed updates the same rows instead of duplicating them.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const db = JSON.parse(fs.readFileSync(path.join(root, 'data/knowledge-base.json'), 'utf8'));

const uuid = id => {
  const h = crypto.createHash('sha1').update('cae-kb-v4:' + id).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-${((parseInt(h.slice(16, 18), 16) & 0x3f) | 0x80).toString(16)}${h.slice(18, 20)}-${h.slice(20, 32)}`;
};
/* local `figures` -> `images` items (the database stores them in entries.images) */
const images = e => (e.figures || [])
  .filter(f => f.defaultVisible !== false)
  .map(f => ({ src: f.src, title: f.title, caption: f.caption, section: f.section, step: f.step, order: f.order, ...(f.key ? { key: true } : {}), mock: true }))
  .concat((e.images || []));

export const categoryRows = db.categories.map(c => ({ key: c.key, label: c.label, parent_key: c.parent_key, description: c.description || '', is_active: c.is_active, sort_order: c.sort_order }));
export const entryRows = db.entries.map(e => ({
  id: uuid(e.id), category: e.category, title: e.title, tags: e.tags || [], symptom: e.symptom || '', root_cause: e.root_cause || '', solution: e.solution || '',
  failed_attempts: e.failed_attempts || [], notes: e.notes || '', reference_source: e.reference_source || '', images: images(e), views: 0,
  created_at: e.created_at, updated_at: e.updated_at
}));

if (process.argv.includes('--rows')) { console.log(JSON.stringify({ categories: categoryRows, entries: entryRows })); process.exit(0); }

/* SQL text literals use dollar quoting, so quotes and backslashes in the content need no escaping */
const q = s => { if (String(s).includes('$q$')) throw new Error('content contains the $q$ delimiter'); return `$q$${s}$q$`; };
const arr = a => a.length ? `array[${a.map(q).join(', ')}]::text[]` : `'{}'::text[]`;
const nul = v => v == null ? 'null' : q(v);

let sql = `-- CAE Knowledge Base V4 — sample data (generated by scripts/build-seed.mjs from data/knowledge-base.json)
-- Run AFTER supabase/schema.sql. Safe to re-run: rows are matched by key / id and updated.
-- All figures in the sample article are generated illustrations (mock) served from the site's own assets/figures folder.

insert into public.software_categories (key, label, parent_key, description, is_active, sort_order) values
`;
// parents must exist before children (foreign key): roots first
const cats = [...categoryRows].sort((a, b) => (a.parent_key ? 1 : 0) - (b.parent_key ? 1 : 0));
sql += cats.map(c => `  (${q(c.key)}, ${q(c.label)}, ${nul(c.parent_key)}, ${q(c.description)}, ${c.is_active}, ${c.sort_order})`).join(',\n');
sql += `
on conflict (key) do update set label = excluded.label, parent_key = excluded.parent_key, description = excluded.description,
  is_active = excluded.is_active, sort_order = excluded.sort_order;

`;
for (const e of entryRows) {
  sql += `insert into public.entries (id, category, title, tags, symptom, root_cause, solution, failed_attempts, notes, reference_source, images, views, created_at, updated_at) values (
  '${e.id}', ${q(e.category)}, ${q(e.title)}, ${arr(e.tags)},
  ${q(e.symptom)},
  ${q(e.root_cause)},
  ${q(e.solution)},
  ${arr(e.failed_attempts)}, ${q(e.notes)}, ${q(e.reference_source)},
  ${q(JSON.stringify(e.images))}::jsonb, ${e.views}, '${e.created_at}', '${e.updated_at}')
on conflict (id) do update set category = excluded.category, title = excluded.title, tags = excluded.tags, symptom = excluded.symptom,
  root_cause = excluded.root_cause, solution = excluded.solution, failed_attempts = excluded.failed_attempts, notes = excluded.notes,
  reference_source = excluded.reference_source, images = excluded.images, created_at = excluded.created_at, updated_at = excluded.updated_at;

`;
}
fs.mkdirSync(path.join(root, 'supabase'), { recursive: true });
fs.writeFileSync(path.join(root, 'supabase/seed.sql'), sql);
console.log(`supabase/seed.sql: ${categoryRows.length} categories, ${entryRows.length} entries`);
